#ifndef _PIN_ASSIGNMENTS_H_
#define _PIN_ASSIGNMENTS_H_

#include <gpin.h>

#define PIN_LIFT_DIR_FL PINHEAD_J11_P5   // GIO B2
#define PIN_LIFT_PWM_FL PINHEAD_J11_P20  // PWM 3
#define PIN_LIFT_SWP_FL PINHEAD_J11_P42  // ADC 17
#define PIN_LIFT_SWN_FL PINHEAD_J11_P6   // GIO B3
#define PIN_LIFT_ADC_FL PINHEAD_J7_P6    // ADC 11
#define PIN_LIFT_DIR_FR PINHEAD_J11_P7   // GIO A0
#define PIN_LIFT_PWM_FR PINHEAD_J11_P24  // PWM 4
#define PIN_LIFT_SWP_FR PINHEAD_J11_P41  // ADC 16
#define PIN_LIFT_SWN_FR PINHEAD_J11_P10  // GIO A1
#define PIN_LIFT_ADC_FR PINHEAD_J7_P5    // ADC 3
#define PIN_LIFT_DIR_BL PINHEAD_J11_P12  // GIO A2
#define PIN_LIFT_PWM_BL PINHEAD_J11_P25  // PWM 5
#define PIN_LIFT_SWP_BL PINHEAD_J11_P44  // ADC 19
#define PIN_LIFT_SWN_BL PINHEAD_J11_P19  // GIO A7
#define PIN_LIFT_ADC_BL PINHEAD_J7_P8    // ADC 12
#define PIN_LIFT_DIR_BR PINHEAD_J11_P18  // GIO A6
#define PIN_LIFT_PWM_BR PINHEAD_J11_P26  // PWM 6
#define PIN_LIFT_SWP_BR PINHEAD_J11_P43  // ADC 18
#define PIN_LIFT_SWN_BR PINHEAD_J11_P16  // GIO A5
#define PIN_LIFT_ADC_BR PINHEAD_J7_P7    // ADC 4

#define PIN_DRIVE_STEP_L PINHEAD_J11_P29 // PWM 12
#define PIN_DRIVE_DIR_L  PINHEAD_J11_P28 // PWM 13
#define PIN_DRIVE_STEP_R PINHEAD_J10_P6  // PWM 10
#define PIN_DRIVE_DIR_R  PINHEAD_J10_P5  // PWM 11

#define PIN_LIFT_BRAKE   PINHEAD_J11_P27 // PWM 7
#define PIN_DRIVE_ENABLE PINHEAD_J10_P8  // GIO B1
#define PIN_DRIVE_CLUTCH PINHEAD_J10_P15 // GIO B0

#endif
